network.host: 0.0.0.0

xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true

network.bind_host: 172.20.0.2
http.port: 9200

node.master: true
node.data: true
