filebeat.inputs:
 - type: log
   paths:
     - /root/logs/*.log
   fields:
       document_type: log
   multilane.type: pattern
   multilane.pattern: '^\s'
   multilane.negate: false
   multilane.match: before


filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: filebeat
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
      fields:
         document_type: docker
output.logstash:
   hosts: 172.20.0.3:5044
